version: '3'
services:
  api:
    build:
      dockerfile: Docker_settings\fastapi\Dockerfiles\Dockerfile
      context: fastapi-solution
    ports:
      - "8000:8000"
    env_file:
      fastapi-solution/.env

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s

  redis:
    build:
      dockerfile: Docker_settings\redis_cache\Dockerfiles\Dockerfile
      context: fastapi-solution

    env_file:
      fastapi-solution/.env
    ports:
      - "6379:6379"
    depends_on:
      - api

networks:
  default:
    external:
      name: app_movies_network
  