version: '3'
services:
  api:
    container_name: fast_api_service
    build:
      dockerfile: Docker_settings/fastapi/Dockerfiles/Dockerfile
      context: fastapi-solution
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      fastapi-solution/.env
    volumes:
      - ./fastapi-solution/src/:/opt/app/src
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    networks:
        - auth_network
        - default

    depends_on:
      - redis
    entrypoint:
      [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --listen 0.0.0.0:5678 -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000",
      ]

  redis:
    container_name: redis_cache
    build:
      dockerfile: Docker_settings/redis_cache/Dockerfiles/Dockerfile
      context: fastapi-solution

    env_file:
      fastapi-solution/.env
    ports:
      - "6379:6379"


networks:
  default:
    external:
      name: app_movies_network
  auth_network:
    name: auth_network
    external: true  