version: '3'
services:
  api:
    container_name: fast_api_service
    build:
      dockerfile: Docker_settings/fastapi/Dockerfiles/Dockerfile
      context: fastapi-solution
    ports:
      - "8000:8000"

    env_file:
      fastapi-solution/.env.sample
    volumes:
      - ./fastapi-solution/src/:/opt/app/src
    depends_on:
      - redis
      - elasticsearch

    entrypoint: [
      "sh",
      "-c",
      "uvicorn src.main:app  --host 0.0.0.0 --port 8000 --reload",
    ]

  redis:
    container_name: redis_cache
    build:
      dockerfile: Docker_settings/redis_cache/Dockerfiles/Dockerfile
      context: fastapi-solution

    env_file:
      fastapi-solution/.env.sample
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: movies_elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    env_file:
      fastapi-solution/.env.sample

  kibana:
    image: kibana:8.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  default:
    external:
      name: app_movies_network