version: "3"

volumes:
  pg_data:
    name: posgre_movies_db
  elastic_volume:
    name: elastic_movies_data
  redis_data:
    name: redis_cache_data

networks:
  app_movies_network:
    driver:
      bridge

services:

  db:
    container_name: movies_db
    restart: always
    build:
      dockerfile: Dockerfiles/Dockerfile
      context: Docker_settings/db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      .env
    ports:
     - "5432:5432"
    networks:
      - app_movies_network

  elastic:
    container_name: movies_elasticsearch
    image: elasticsearch:8.6.2
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app_movies_network
    depends_on:
      - db

  etl:
    container_name: etl_pg_to_elastic
    restart: always
    build:
      dockerfile: Docker_settings/etl/Dockerfiles/Dockerfile
      context: .
    networks:
      - app_movies_network
    depends_on:
      - elastic
    env_file:
      .env

  redis:
    build:
      dockerfile: Dockerfiles/Dockerfile
      context: Docker_settings/redis_cache
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_movies_network

  fastapi:
    container_name: fastapi_service
    restart: always
    build:
      dockerfile: Docker_settings/fastapi/Dockerfiles/Dockerfile
      context: .
    networks:
      - app_movies_network
    ports:
      - "8008:8008"
    env_file:
      - .env
    depends_on:
      - redis 
      - elastic
